In [1]:
import random
from gensim.models import Word2Vec

In [ ]:
import pickle as pkl

In [ ]:
import nltk
from nltk.corpus import wordnet

# Ensure the WordNet corpus is downloaded
nltk.download('wordnet', quiet=True)

True

In [ ]:
df = pkl.load(open('C:\\Users\\tjsss\\OneDrive\\Desktop\\machine learning\\earthquakeIDSS\\earthquakeDSS\\data\\cleanedtext_data.pkl', 'rb'))
df

,tweet_id,tweet_text,label,clean_text
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,guys northem chile really needs a suppomessage...
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,rehearsal time w amp teamdeb for hitparade amp...
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,happy b day happyhyukday
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,my heagoes out to the victims of the 8 2 magni...
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,chile earthquake 5 dead several seriously injured
...,...,...,...,...
1927,451278786491715584,Disaster declared after Chile quake: Chile dec...,other_useful_information,disaster declared after chile quake chile decl...
1928,451444407792070656,"Chile assesses damage after massive quake, tsu...",infrastructure_and_utilities_damage,chile assesses damage after massive quake tsun...
1929,455063017361666048,RT @AvrilLavigne: Thinking of everyone in Chil...,sympathy_and_emotional_support,thinking of everyone in chile today hope all o...
1930,452613086289989632,I hope that @justinbieber will follow me.I'm s...,not_related_or_irrelevant,i hope that will follow me i m still waiting f...
1931,451256853557547009,"#PrayForChile They've prayed for us, Philippin...",sympathy_and_emotional_support,prayforchile they ve prayed for us philippines...

In [26]:
print(wordnet.synsets('program'))

[Synset('plan.n.01'), Synset('program.n.02'), Synset('broadcast.n.02'), Synset('platform.n.02'), Synset('program.n.05'), Synset('course_of_study.n.01'), Synset('program.n.07'), Synset('program.n.08'), Synset('program.v.01'), Synset('program.v.02')]

In [27]:
df

,tweet_id,tweet_text,label,clean_text,augmented_sentences
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,guys northem chile really needs a suppomessage...,[guys northem chile really needs a suppomessag...
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,rehearsal time w amp teamdeb for hitparade amp...,[rehearsal time w amp teamdeb for hitparade am...
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,happy b day happyhyukday,"[happy b day happyhyukday, happy b day happyhy..."
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,my heagoes out to the victims of the 8 2 magni...,[my heagoes out to the victims of the 8 2 magn...
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,chile earthquake 5 dead several seriously injured,[chile earthquake 5 dead several seriously inj...
...,...,...,...,...,...
1927,451278786491715584,Disaster declared after Chile quake: Chile dec...,other_useful_information,disaster declared after chile quake chile decl...,[disaster declared after chile quake chile dec...
1928,451444407792070656,"Chile assesses damage after massive quake, tsu...",infrastructure_and_utilities_damage,chile assesses damage after massive quake tsun...,[chile assesses damage after massive quake tsu...
1929,455063017361666048,RT @AvrilLavigne: Thinking of everyone in Chil...,sympathy_and_emotional_support,thinking of everyone in chile today hope all o...,[thinking of everyone in chile today hope all ...
1930,452613086289989632,I hope that @justinbieber will follow me.I'm s...,not_related_or_irrelevant,i hope that will follow me i m still waiting f...,[i hope that will follow me i m still waiting ...
1931,451256853557547009,"#PrayForChile They've prayed for us, Philippin...",sympathy_and_emotional_support,prayforchile they ve prayed for us philippines...,[prayforchile they ve prayed for us philippine...

In [28]:
new_severity_map = {
    "injured_or_dead_people":3,
    "missing_trapped_or_found_people":3,
    "displaced_people_and_evacuations":3,
    "infrastructure_and_utilities_damage":3,
    "donation_needs_or_offers_or_volunteering_services":2,
    "caution_and_advice":2,
    "sympathy_and_emotional_support":1,
    "other_useful_information":1,
    "not_related_or_irrelevant":0
}

In [29]:
df['severity_class'] = df['label'].map(new_severity_map)

In [30]:
df

,tweet_id,tweet_text,label,clean_text,augmented_sentences,severity_class
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,guys northem chile really needs a suppomessage...,[guys northem chile really needs a suppomessag...,1
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,rehearsal time w amp teamdeb for hitparade amp...,[rehearsal time w amp teamdeb for hitparade am...,0
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,happy b day happyhyukday,"[happy b day happyhyukday, happy b day happyhy...",0
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,my heagoes out to the victims of the 8 2 magni...,[my heagoes out to the victims of the 8 2 magn...,1
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,chile earthquake 5 dead several seriously injured,[chile earthquake 5 dead several seriously inj...,3
...,...,...,...,...,...,...
1927,451278786491715584,Disaster declared after Chile quake: Chile dec...,other_useful_information,disaster declared after chile quake chile decl...,[disaster declared after chile quake chile dec...,1
1928,451444407792070656,"Chile assesses damage after massive quake, tsu...",infrastructure_and_utilities_damage,chile assesses damage after massive quake tsun...,[chile assesses damage after massive quake tsu...,3
1929,455063017361666048,RT @AvrilLavigne: Thinking of everyone in Chil...,sympathy_and_emotional_support,thinking of everyone in chile today hope all o...,[thinking of everyone in chile today hope all ...,1
1930,452613086289989632,I hope that @justinbieber will follow me.I'm s...,not_related_or_irrelevant,i hope that will follow me i m still waiting f...,[i hope that will follow me i m still waiting ...,0
1931,451256853557547009,"#PrayForChile They've prayed for us, Philippin...",sympathy_and_emotional_support,prayforchile they ve prayed for us philippines...,[prayforchile they ve prayed for us philippine...,1

In [31]:
print(df['augmented_sentences'].iloc[0] , '\n' , df['clean_text'].iloc[0])

['guys northem chile really needs a suppomessage prayforchile', 'guys northem chile really needs a suppomessage prayforchile', 'guys northem chile really needs a suppomessage prayforchile', 'guys northem chile really needs a suppomessage prayforchile', 'guys northem chile really needs a suppomessage prayforchile']
 guys northem chile really needs a suppomessage prayforchile

In [41]:
import tqdm
import pandas as pd
from tqdm import tqdm

In [ ]:
_synonym_cache = {}

def get_synonyms(word: str) -> list:
    """Fetch synonyms from WordNet with caching."""
    if word in _synonym_cache:
        return _synonym_cache[word]
    synonyms = set()
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            candidate = lemma.name().replace('_', ' ').replace('-', ' ').lower()
            if candidate != word.lower():          
                synonyms.add(candidate)
    result = list(synonyms)
    _synonym_cache[word] = result
    return result


def synonym_replacement(sentence: str, replace_prob: float = 0.4) -> str:

    words = sentence.split()
    new_words = []

    for word in words:

        if len(word) <= 2 or word == "":          
            new_words.append(word)
            continue

        synonyms = get_synonyms(word)

        if synonyms and random.random() < replace_prob:
            new_words.append(random.choice(synonyms))   
        else:
            new_words.append(word)                       

    return " ".join(new_words)


def augment_sentence_wn(sentence: str, num_augmented: int = 3, replace_prob: float = 0.4) -> list:
    
    return [
        synonym_replacement(sentence, replace_prob)
        for _ in range(num_augmented)
    ]


# ── Loop over full training DataFrame ────────────────────────────────────────

def apply_wn_augmentation(df: pd.DataFrame, text_col: str = "clean_text", label_col: str = "severity_class", target_classes: list = None, num_augmented: int = 3,replace_prob: float = 0.4,random_seed: int = 42) -> pd.DataFrame:
    
    random.seed(random_seed)

    if target_classes is not None:
        df_to_aug = df[df[label_col].isin(target_classes)].copy()
        df_no_aug = df[~df[label_col].isin(target_classes)].copy()
        print(f"Augmenting classes: {target_classes} "
              f"({len(df_to_aug)} samples) | Skipping: {len(df_no_aug)} samples")
    else:
        df_to_aug = df.copy()
        df_no_aug = pd.DataFrame(columns=df.columns)

    augmented_rows = []

    for _, row in tqdm(df_to_aug.iterrows(), total=len(df_to_aug), desc="WN Augmentation"):
        original_text = str(row[text_col])
        aug_texts = augment_sentence_wn(
            original_text,
            num_augmented=num_augmented,
            replace_prob=replace_prob
        )
        for aug_text in aug_texts:
            new_row = row.copy()
            new_row[text_col] = aug_text
            new_row["augmented"] = True
            augmented_rows.append(new_row)

    df_original = df.copy()
    df_original["augmented"] = False

    if augmented_rows:
        df_aug = pd.DataFrame(augmented_rows)
        df_combined = pd.concat([df_original, df_aug], ignore_index=True)
    else:
        df_combined = df_original

    df_combined = df_combined.sample(frac=1, random_state=random_seed).reset_index(drop=True)

    print(f"\n✅ WN Augmentation complete.")
    print(f"   Original : {len(df_original)}")
    print(f"   Generated: {len(augmented_rows)}")
    print(f"   Total    : {len(df_combined)}")
    print(f"\nNew class distribution:")
    print(df_combined[label_col].value_counts().sort_index())

    return df_combined

In [44]:
df

,tweet_id,tweet_text,label,clean_text,severity_class
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,guys northem chile really needs a suppomessage...,1
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,rehearsal time w amp teamdeb for hitparade amp...,0
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,happy b day happyhyukday,0
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,my heagoes out to the victims of the 8 2 magni...,1
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,chile earthquake 5 dead several seriously injured,3
...,...,...,...,...,...
1927,451278786491715584,Disaster declared after Chile quake: Chile dec...,other_useful_information,disaster declared after chile quake chile decl...,1
1928,451444407792070656,"Chile assesses damage after massive quake, tsu...",infrastructure_and_utilities_damage,chile assesses damage after massive quake tsun...,3
1929,455063017361666048,RT @AvrilLavigne: Thinking of everyone in Chil...,sympathy_and_emotional_support,thinking of everyone in chile today hope all o...,1
1930,452613086289989632,I hope that @justinbieber will follow me.I'm s...,not_related_or_irrelevant,i hope that will follow me i m still waiting f...,0
1931,451256853557547009,"#PrayForChile They've prayed for us, Philippin...",sympathy_and_emotional_support,prayforchile they ve prayed for us philippines...,1

In [45]:
from sklearn.model_selection import train_test_split

In [46]:

df_train, df_test = train_test_split(df, test_size=0.2, random_state=42, stratify=df['severity_class'])

In [49]:
df_train_aug = apply_wn_augmentation(
    df_train,
    target_classes=[0, 2, 3],     # skip class 1 (high) — already dominant
    num_augmented=3,               # 3 new versions per sample
    replace_prob=0.4)

Augmenting classes: [0, 2, 3] (647 samples) | Skipping: 898 samples

WN Augmentation: 100%|██████████| 647/647 [00:02<00:00, 229.29it/s]

✅ WN Augmentation complete.
   Original : 1545
   Generated: 1941
   Total    : 3486

New class distribution:
severity_class
0    1092
1     898
2     820
3     676
Name: count, dtype: int64

In [68]:
print("=== DUPLICATE CHECK ===")
print(f"Total rows: {len(df_train_aug)}")
print(f"Unique tweet_ids: {df_train_aug['tweet_id'].nunique()}")
print(f"Duplicate tweet_ids count: {df_train_aug['tweet_id'].duplicated().sum()}")

# Step 2: Show ANY duplicates if they exist
if df_train_aug['tweet_id'].duplicated().any():
    print("\n=== FIRST DUPLICATE EXAMPLE ===")
    dup_mask = df_train_aug.duplicated(subset=['tweet_id'], keep=False)
    print(df_train_aug[dup_mask][['tweet_id', 'tweet_text', 'severity_class']].head(10))
else:
    print("\n✅ NO DUPLICATES FOUND")

# Step 3: Show top 5 most frequent tweet_ids (should be 1 if no dups)
print("\n=== TOP 5 FREQUENCIES ===")
print(df_train_aug['tweet_id'].value_counts().head())

=== DUPLICATE CHECK ===
Total rows: 3486
Unique tweet_ids: 1545
Duplicate tweet_ids count: 1941

=== FIRST DUPLICATE EXAMPLE ===
              tweet_id                                         tweet_text  \
1   451601130921795584  UPDATE 7-New earthquake in Chile prompts tsuna...
2   451615317253320704  RT @NewsBreaker: NOW:  Chileâs Navy issues t...
4   451595490044309504  RT @Avigain10: 70 days till the World Cup. Whe...
5   451248861802397696  NEWS: more on a 8.2 quake off Chile, with tsun...
6   451563907576913920  RT @FibreNews: #BREAKING: A magnitude 7.8 #ear...
7   451851839055462400         @justinbieber see me please ! its my dream
8   452339576309170176  @mydarlingdrew que suertuda eres, te sigue Jus...
9   452481423962681345      #nowplaying  Mood for love - @DemiLouiseMusic
10  451460867217821696  RT @coreyspowell: The #Chile quake in context:...
11  451247182956331008  RT @CKNW: #Tsunami risk to #Hawaii being evalu...

    severity_class
1                2
2                2
4                0
5                2
6                2
7                0
8                0
9                0
10               2
11               2

=== TOP 5 FREQUENCIES ===
tweet_id
452481423962681345    4
451460867217821696    4
451247182956331008    4
451601130921795584    4
451615317253320704    4
Name: count, dtype: int64

In [73]:
# Pick one tweet_id and see all its versions
example_id = 451460867217821696  # From your top frequencies
print("=== EXAMPLE AUGMENTATION ===")
example_rows = df_train_aug[df_train_aug['tweet_id'] == example_id]
print(example_rows[['clean_text', 'severity_class']])

=== EXAMPLE AUGMENTATION ===
                                             clean_text  severity_class
10    the republic of chile palpitate in context a m...               2
1210  the chile seism in setting a function of all s...               2
1295  the chile quake in setting a single valued fun...               2
2013  the chile quake in context a map of all seismi...               2

In [77]:
df_train_aug.drop('augmented', axis=1, inplace=True)

In [78]:
df_train_aug.head()

,tweet_id,label,clean_text,severity_class
0,451303436211200000,sympathy_and_emotional_support,only just read about the earthquake in chile t...,1
1,451601130921795584,caution_and_advice,update 7 new earthquake in republic of chile p...,2
2,451615317253320704,caution_and_advice,right away chile s navy issues tsunami warning...,2
3,451496902706470912,sympathy_and_emotional_support,i really dont have that much info about the ea...,1
4,451595490044309504,not_related_or_irrelevant,70 days till the world cup where we will all b...,0

In [79]:
pkl.dump(df_train_aug, open('C:\\Users\\tjsss\\OneDrive\\Desktop\\machine learning\\earthquakeIDSS\\earthquakeDSS\\data\\train_augmented.pkl', 'wb'))